/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Accounts API
 * Accounts management service API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalAdapterHttpHandlerMfaAssignTOTPRequest,
  InternalAdapterHttpHandlerMfaAssignTOTPResponse,
  InternalAdapterHttpHandlerMfaGetMFAResponse,
  InternalAdapterHttpHandlerMfaListMFAResponse,
  InternalAdapterHttpHandlerMfaRemoveMFAResponse,
  InternalAdapterHttpHandlerMfaUpdateMFARequest,
  InternalAdapterHttpHandlerMfaUpdateMFAResponse,
  InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest,
  InternalAdapterHttpHandlerMfaVerifyTOTPAssignResponse,
  InternalAdapterHttpHandlerProfileGetProfileResponse,
  InternalAdapterHttpHandlerProfileUpdateProfileRequest,
  InternalAdapterHttpHandlerProfileUpdateProfileResponse,
  InternalAdapterHttpHandlerUserDeleteAccountResponse,
  InternalAdapterHttpHandlerUserRegisterRequest,
  InternalAdapterHttpHandlerUserRegisterResponse,
  MerrmidErrorResponse
} from './schemas/accounts';

/**
 * Delete the authenticated user's account
 * @summary Delete account
 */
export type deleteV1AccountResponse200 = {
  data: InternalAdapterHttpHandlerUserDeleteAccountResponse
  status: 200
}

export type deleteV1AccountResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type deleteV1AccountResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type deleteV1AccountResponseSuccess = (deleteV1AccountResponse200) & {
  headers: Headers;
};
export type deleteV1AccountResponseError = (deleteV1AccountResponse401 | deleteV1AccountResponse500) & {
  headers: Headers;
};

export type deleteV1AccountResponse = (deleteV1AccountResponseSuccess | deleteV1AccountResponseError)

export const getDeleteV1AccountUrl = () => {




  return `https://accounts.mandacode.com/api/v1/account`
}

export const deleteV1Account = async (options?: RequestInit): Promise<deleteV1AccountResponse> => {

  const res = await fetch(getDeleteV1AccountUrl(),
    {
      ...options,
      method: 'DELETE'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1AccountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteV1AccountResponse
}




export const getDeleteV1AccountMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteV1Account>>, TError, void, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof deleteV1Account>>, TError, void, TContext> => {

  const mutationKey = ['deleteV1Account'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1Account>>, void> = () => {


    return deleteV1Account(fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type DeleteV1AccountMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1Account>>>

export type DeleteV1AccountMutationError = MerrmidErrorResponse

/**
* @summary Delete account
*/
export const useDeleteV1Account = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteV1Account>>, TError, void, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof deleteV1Account>>,
      TError,
      void,
      TContext
    > => {
  return useMutation(getDeleteV1AccountMutationOptions(options), queryClient);
}

/**
 * List all MFA (Multi-Factor Authentication) devices for the authenticated user
 * @summary List MFA devices
 */
export type getV1MfaResponse200 = {
  data: InternalAdapterHttpHandlerMfaListMFAResponse
  status: 200
}

export type getV1MfaResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type getV1MfaResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type getV1MfaResponseSuccess = (getV1MfaResponse200) & {
  headers: Headers;
};
export type getV1MfaResponseError = (getV1MfaResponse401 | getV1MfaResponse500) & {
  headers: Headers;
};

export type getV1MfaResponse = (getV1MfaResponseSuccess | getV1MfaResponseError)

export const getGetV1MfaUrl = () => {




  return `https://accounts.mandacode.com/api/v1/mfa`
}

export const getV1Mfa = async (options?: RequestInit): Promise<getV1MfaResponse> => {

  const res = await fetch(getGetV1MfaUrl(),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MfaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1MfaResponse
}





export const getGetV1MfaQueryKey = () => {
  return [
    `https://accounts.mandacode.com/api/v1/mfa`
  ] as const;
}


export const getGetV1MfaQueryOptions = <TData = Awaited<ReturnType<typeof getV1Mfa>>, TError = MerrmidErrorResponse>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Mfa>>, TError, TData>>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1MfaQueryKey();



  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Mfa>>> = ({ signal }) => getV1Mfa({ signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getV1Mfa>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1MfaQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Mfa>>>
export type GetV1MfaQueryError = MerrmidErrorResponse


export function useGetV1Mfa<TData = Awaited<ReturnType<typeof getV1Mfa>>, TError = MerrmidErrorResponse>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Mfa>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getV1Mfa>>,
        TError,
        Awaited<ReturnType<typeof getV1Mfa>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Mfa<TData = Awaited<ReturnType<typeof getV1Mfa>>, TError = MerrmidErrorResponse>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Mfa>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getV1Mfa>>,
        TError,
        Awaited<ReturnType<typeof getV1Mfa>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Mfa<TData = Awaited<ReturnType<typeof getV1Mfa>>, TError = MerrmidErrorResponse>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Mfa>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List MFA devices
 */

export function useGetV1Mfa<TData = Awaited<ReturnType<typeof getV1Mfa>>, TError = MerrmidErrorResponse>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Mfa>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1MfaQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Assign a new TOTP (Time-based One-Time Password) to the authenticated user
 * @summary Assign TOTP
 */
export type postV1MfaTotpResponse200 = {
  data: InternalAdapterHttpHandlerMfaAssignTOTPResponse
  status: 200
}

export type postV1MfaTotpResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1MfaTotpResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1MfaTotpResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type postV1MfaTotpResponseSuccess = (postV1MfaTotpResponse200) & {
  headers: Headers;
};
export type postV1MfaTotpResponseError = (postV1MfaTotpResponse400 | postV1MfaTotpResponse401 | postV1MfaTotpResponse500) & {
  headers: Headers;
};

export type postV1MfaTotpResponse = (postV1MfaTotpResponseSuccess | postV1MfaTotpResponseError)

export const getPostV1MfaTotpUrl = () => {




  return `https://accounts.mandacode.com/api/v1/mfa/totp`
}

export const postV1MfaTotp = async (internalAdapterHttpHandlerMfaAssignTOTPRequest: InternalAdapterHttpHandlerMfaAssignTOTPRequest, options?: RequestInit): Promise<postV1MfaTotpResponse> => {

  const res = await fetch(getPostV1MfaTotpUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        internalAdapterHttpHandlerMfaAssignTOTPRequest,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1MfaTotpResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1MfaTotpResponse
}




export const getPostV1MfaTotpMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1MfaTotp>>, TError, { data: InternalAdapterHttpHandlerMfaAssignTOTPRequest }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof postV1MfaTotp>>, TError, { data: InternalAdapterHttpHandlerMfaAssignTOTPRequest }, TContext> => {

  const mutationKey = ['postV1MfaTotp'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1MfaTotp>>, { data: InternalAdapterHttpHandlerMfaAssignTOTPRequest }> = (props) => {
    const { data } = props ?? {};

    return postV1MfaTotp(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type PostV1MfaTotpMutationResult = NonNullable<Awaited<ReturnType<typeof postV1MfaTotp>>>
export type PostV1MfaTotpMutationBody = InternalAdapterHttpHandlerMfaAssignTOTPRequest
export type PostV1MfaTotpMutationError = MerrmidErrorResponse

/**
* @summary Assign TOTP
*/
export const usePostV1MfaTotp = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1MfaTotp>>, TError, { data: InternalAdapterHttpHandlerMfaAssignTOTPRequest }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof postV1MfaTotp>>,
      TError,
      { data: InternalAdapterHttpHandlerMfaAssignTOTPRequest },
      TContext
    > => {
  return useMutation(getPostV1MfaTotpMutationOptions(options), queryClient);
}

/**
 * Verify the TOTP code after assigning a new TOTP using session key. The TOTP must be verified to become active.
 * @summary Verify TOTP Assignment
 */
export type postV1MfaTotpVerifyResponse200 = {
  data: InternalAdapterHttpHandlerMfaVerifyTOTPAssignResponse
  status: 200
}

export type postV1MfaTotpVerifyResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1MfaTotpVerifyResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1MfaTotpVerifyResponse404 = {
  data: MerrmidErrorResponse
  status: 404
}

export type postV1MfaTotpVerifyResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type postV1MfaTotpVerifyResponseSuccess = (postV1MfaTotpVerifyResponse200) & {
  headers: Headers;
};
export type postV1MfaTotpVerifyResponseError = (postV1MfaTotpVerifyResponse400 | postV1MfaTotpVerifyResponse401 | postV1MfaTotpVerifyResponse404 | postV1MfaTotpVerifyResponse500) & {
  headers: Headers;
};

export type postV1MfaTotpVerifyResponse = (postV1MfaTotpVerifyResponseSuccess | postV1MfaTotpVerifyResponseError)

export const getPostV1MfaTotpVerifyUrl = () => {




  return `https://accounts.mandacode.com/api/v1/mfa/totp/verify`
}

export const postV1MfaTotpVerify = async (internalAdapterHttpHandlerMfaVerifyTOTPAssignRequest: InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest, options?: RequestInit): Promise<postV1MfaTotpVerifyResponse> => {

  const res = await fetch(getPostV1MfaTotpVerifyUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        internalAdapterHttpHandlerMfaVerifyTOTPAssignRequest,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1MfaTotpVerifyResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1MfaTotpVerifyResponse
}




export const getPostV1MfaTotpVerifyMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1MfaTotpVerify>>, TError, { data: InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof postV1MfaTotpVerify>>, TError, { data: InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest }, TContext> => {

  const mutationKey = ['postV1MfaTotpVerify'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1MfaTotpVerify>>, { data: InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest }> = (props) => {
    const { data } = props ?? {};

    return postV1MfaTotpVerify(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type PostV1MfaTotpVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof postV1MfaTotpVerify>>>
export type PostV1MfaTotpVerifyMutationBody = InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest
export type PostV1MfaTotpVerifyMutationError = MerrmidErrorResponse

/**
* @summary Verify TOTP Assignment
*/
export const usePostV1MfaTotpVerify = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1MfaTotpVerify>>, TError, { data: InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof postV1MfaTotpVerify>>,
      TError,
      { data: InternalAdapterHttpHandlerMfaVerifyTOTPAssignRequest },
      TContext
    > => {
  return useMutation(getPostV1MfaTotpVerifyMutationOptions(options), queryClient);
}

/**
 * Retrieve a specific MFA (Multi-Factor Authentication) device by ID
 * @summary Get MFA device
 */
export type getV1MfaMfaIdResponse200 = {
  data: InternalAdapterHttpHandlerMfaGetMFAResponse
  status: 200
}

export type getV1MfaMfaIdResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type getV1MfaMfaIdResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type getV1MfaMfaIdResponse403 = {
  data: MerrmidErrorResponse
  status: 403
}

export type getV1MfaMfaIdResponse404 = {
  data: MerrmidErrorResponse
  status: 404
}

export type getV1MfaMfaIdResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type getV1MfaMfaIdResponseSuccess = (getV1MfaMfaIdResponse200) & {
  headers: Headers;
};
export type getV1MfaMfaIdResponseError = (getV1MfaMfaIdResponse400 | getV1MfaMfaIdResponse401 | getV1MfaMfaIdResponse403 | getV1MfaMfaIdResponse404 | getV1MfaMfaIdResponse500) & {
  headers: Headers;
};

export type getV1MfaMfaIdResponse = (getV1MfaMfaIdResponseSuccess | getV1MfaMfaIdResponseError)

export const getGetV1MfaMfaIdUrl = (mfaId: string,) => {




  return `https://accounts.mandacode.com/api/v1/mfa/${mfaId}`
}

export const getV1MfaMfaId = async (mfaId: string, options?: RequestInit): Promise<getV1MfaMfaIdResponse> => {

  const res = await fetch(getGetV1MfaMfaIdUrl(mfaId),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1MfaMfaIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1MfaMfaIdResponse
}





export const getGetV1MfaMfaIdQueryKey = (mfaId: string,) => {
  return [
    `https://accounts.mandacode.com/api/v1/mfa/${mfaId}`
  ] as const;
}


export const getGetV1MfaMfaIdQueryOptions = <TData = Awaited<ReturnType<typeof getV1MfaMfaId>>, TError = MerrmidErrorResponse>(mfaId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MfaMfaId>>, TError, TData>>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1MfaMfaIdQueryKey(mfaId);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1MfaMfaId>>> = ({ signal }) => getV1MfaMfaId(mfaId, { signal, ...fetchOptions });





  return { queryKey, queryFn, enabled: !!(mfaId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getV1MfaMfaId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1MfaMfaIdQueryResult = NonNullable<Awaited<ReturnType<typeof getV1MfaMfaId>>>
export type GetV1MfaMfaIdQueryError = MerrmidErrorResponse


export function useGetV1MfaMfaId<TData = Awaited<ReturnType<typeof getV1MfaMfaId>>, TError = MerrmidErrorResponse>(
  mfaId: string, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MfaMfaId>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getV1MfaMfaId>>,
        TError,
        Awaited<ReturnType<typeof getV1MfaMfaId>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1MfaMfaId<TData = Awaited<ReturnType<typeof getV1MfaMfaId>>, TError = MerrmidErrorResponse>(
  mfaId: string, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MfaMfaId>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getV1MfaMfaId>>,
        TError,
        Awaited<ReturnType<typeof getV1MfaMfaId>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1MfaMfaId<TData = Awaited<ReturnType<typeof getV1MfaMfaId>>, TError = MerrmidErrorResponse>(
  mfaId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MfaMfaId>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get MFA device
 */

export function useGetV1MfaMfaId<TData = Awaited<ReturnType<typeof getV1MfaMfaId>>, TError = MerrmidErrorResponse>(
  mfaId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1MfaMfaId>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1MfaMfaIdQueryOptions(mfaId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Update a specific MFA (Multi-Factor Authentication) device by ID
 * @summary Update MFA device
 */
export type putV1MfaMfaIdResponse200 = {
  data: InternalAdapterHttpHandlerMfaUpdateMFAResponse
  status: 200
}

export type putV1MfaMfaIdResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type putV1MfaMfaIdResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type putV1MfaMfaIdResponse403 = {
  data: MerrmidErrorResponse
  status: 403
}

export type putV1MfaMfaIdResponse404 = {
  data: MerrmidErrorResponse
  status: 404
}

export type putV1MfaMfaIdResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type putV1MfaMfaIdResponseSuccess = (putV1MfaMfaIdResponse200) & {
  headers: Headers;
};
export type putV1MfaMfaIdResponseError = (putV1MfaMfaIdResponse400 | putV1MfaMfaIdResponse401 | putV1MfaMfaIdResponse403 | putV1MfaMfaIdResponse404 | putV1MfaMfaIdResponse500) & {
  headers: Headers;
};

export type putV1MfaMfaIdResponse = (putV1MfaMfaIdResponseSuccess | putV1MfaMfaIdResponseError)

export const getPutV1MfaMfaIdUrl = (mfaId: string,) => {




  return `https://accounts.mandacode.com/api/v1/mfa/${mfaId}`
}

export const putV1MfaMfaId = async (mfaId: string,
  internalAdapterHttpHandlerMfaUpdateMFARequest: InternalAdapterHttpHandlerMfaUpdateMFARequest, options?: RequestInit): Promise<putV1MfaMfaIdResponse> => {

  const res = await fetch(getPutV1MfaMfaIdUrl(mfaId),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        internalAdapterHttpHandlerMfaUpdateMFARequest,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putV1MfaMfaIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putV1MfaMfaIdResponse
}




export const getPutV1MfaMfaIdMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof putV1MfaMfaId>>, TError, { mfaId: string; data: InternalAdapterHttpHandlerMfaUpdateMFARequest }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof putV1MfaMfaId>>, TError, { mfaId: string; data: InternalAdapterHttpHandlerMfaUpdateMFARequest }, TContext> => {

  const mutationKey = ['putV1MfaMfaId'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putV1MfaMfaId>>, { mfaId: string; data: InternalAdapterHttpHandlerMfaUpdateMFARequest }> = (props) => {
    const { mfaId, data } = props ?? {};

    return putV1MfaMfaId(mfaId, data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type PutV1MfaMfaIdMutationResult = NonNullable<Awaited<ReturnType<typeof putV1MfaMfaId>>>
export type PutV1MfaMfaIdMutationBody = InternalAdapterHttpHandlerMfaUpdateMFARequest
export type PutV1MfaMfaIdMutationError = MerrmidErrorResponse

/**
* @summary Update MFA device
*/
export const usePutV1MfaMfaId = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof putV1MfaMfaId>>, TError, { mfaId: string; data: InternalAdapterHttpHandlerMfaUpdateMFARequest }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof putV1MfaMfaId>>,
      TError,
      { mfaId: string; data: InternalAdapterHttpHandlerMfaUpdateMFARequest },
      TContext
    > => {
  return useMutation(getPutV1MfaMfaIdMutationOptions(options), queryClient);
}

/**
 * Remove a specific MFA (Multi-Factor Authentication) device by ID
 * @summary Remove MFA device
 */
export type deleteV1MfaMfaIdResponse200 = {
  data: InternalAdapterHttpHandlerMfaRemoveMFAResponse
  status: 200
}

export type deleteV1MfaMfaIdResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type deleteV1MfaMfaIdResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type deleteV1MfaMfaIdResponse404 = {
  data: MerrmidErrorResponse
  status: 404
}

export type deleteV1MfaMfaIdResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type deleteV1MfaMfaIdResponseSuccess = (deleteV1MfaMfaIdResponse200) & {
  headers: Headers;
};
export type deleteV1MfaMfaIdResponseError = (deleteV1MfaMfaIdResponse400 | deleteV1MfaMfaIdResponse401 | deleteV1MfaMfaIdResponse404 | deleteV1MfaMfaIdResponse500) & {
  headers: Headers;
};

export type deleteV1MfaMfaIdResponse = (deleteV1MfaMfaIdResponseSuccess | deleteV1MfaMfaIdResponseError)

export const getDeleteV1MfaMfaIdUrl = (mfaId: string,) => {




  return `https://accounts.mandacode.com/api/v1/mfa/${mfaId}`
}

export const deleteV1MfaMfaId = async (mfaId: string, options?: RequestInit): Promise<deleteV1MfaMfaIdResponse> => {

  const res = await fetch(getDeleteV1MfaMfaIdUrl(mfaId),
    {
      ...options,
      method: 'DELETE'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteV1MfaMfaIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteV1MfaMfaIdResponse
}




export const getDeleteV1MfaMfaIdMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteV1MfaMfaId>>, TError, { mfaId: string }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof deleteV1MfaMfaId>>, TError, { mfaId: string }, TContext> => {

  const mutationKey = ['deleteV1MfaMfaId'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteV1MfaMfaId>>, { mfaId: string }> = (props) => {
    const { mfaId } = props ?? {};

    return deleteV1MfaMfaId(mfaId, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type DeleteV1MfaMfaIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteV1MfaMfaId>>>

export type DeleteV1MfaMfaIdMutationError = MerrmidErrorResponse

/**
* @summary Remove MFA device
*/
export const useDeleteV1MfaMfaId = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteV1MfaMfaId>>, TError, { mfaId: string }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof deleteV1MfaMfaId>>,
      TError,
      { mfaId: string },
      TContext
    > => {
  return useMutation(getDeleteV1MfaMfaIdMutationOptions(options), queryClient);
}

/**
 * Get the authenticated user's profile
 * @summary Get profile
 */
export type getV1ProfileResponse200 = {
  data: InternalAdapterHttpHandlerProfileGetProfileResponse
  status: 200
}

export type getV1ProfileResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type getV1ProfileResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type getV1ProfileResponseSuccess = (getV1ProfileResponse200) & {
  headers: Headers;
};
export type getV1ProfileResponseError = (getV1ProfileResponse401 | getV1ProfileResponse500) & {
  headers: Headers;
};

export type getV1ProfileResponse = (getV1ProfileResponseSuccess | getV1ProfileResponseError)

export const getGetV1ProfileUrl = () => {




  return `https://accounts.mandacode.com/api/v1/profile`
}

export const getV1Profile = async (options?: RequestInit): Promise<getV1ProfileResponse> => {

  const res = await fetch(getGetV1ProfileUrl(),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getV1ProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getV1ProfileResponse
}





export const getGetV1ProfileQueryKey = () => {
  return [
    `https://accounts.mandacode.com/api/v1/profile`
  ] as const;
}


export const getGetV1ProfileQueryOptions = <TData = Awaited<ReturnType<typeof getV1Profile>>, TError = MerrmidErrorResponse>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Profile>>, TError, TData>>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetV1ProfileQueryKey();



  const queryFn: QueryFunction<Awaited<ReturnType<typeof getV1Profile>>> = ({ signal }) => getV1Profile({ signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getV1Profile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetV1ProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getV1Profile>>>
export type GetV1ProfileQueryError = MerrmidErrorResponse


export function useGetV1Profile<TData = Awaited<ReturnType<typeof getV1Profile>>, TError = MerrmidErrorResponse>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Profile>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getV1Profile>>,
        TError,
        Awaited<ReturnType<typeof getV1Profile>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Profile<TData = Awaited<ReturnType<typeof getV1Profile>>, TError = MerrmidErrorResponse>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Profile>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getV1Profile>>,
        TError,
        Awaited<ReturnType<typeof getV1Profile>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetV1Profile<TData = Awaited<ReturnType<typeof getV1Profile>>, TError = MerrmidErrorResponse>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Profile>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get profile
 */

export function useGetV1Profile<TData = Awaited<ReturnType<typeof getV1Profile>>, TError = MerrmidErrorResponse>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getV1Profile>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetV1ProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * Update the authenticated user's profile
 * @summary Update profile
 */
export type putV1ProfileResponse200 = {
  data: InternalAdapterHttpHandlerProfileUpdateProfileResponse
  status: 200
}

export type putV1ProfileResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type putV1ProfileResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type putV1ProfileResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type putV1ProfileResponseSuccess = (putV1ProfileResponse200) & {
  headers: Headers;
};
export type putV1ProfileResponseError = (putV1ProfileResponse400 | putV1ProfileResponse401 | putV1ProfileResponse500) & {
  headers: Headers;
};

export type putV1ProfileResponse = (putV1ProfileResponseSuccess | putV1ProfileResponseError)

export const getPutV1ProfileUrl = () => {




  return `https://accounts.mandacode.com/api/v1/profile`
}

export const putV1Profile = async (internalAdapterHttpHandlerProfileUpdateProfileRequest: InternalAdapterHttpHandlerProfileUpdateProfileRequest, options?: RequestInit): Promise<putV1ProfileResponse> => {

  const res = await fetch(getPutV1ProfileUrl(),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        internalAdapterHttpHandlerProfileUpdateProfileRequest,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putV1ProfileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putV1ProfileResponse
}




export const getPutV1ProfileMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof putV1Profile>>, TError, { data: InternalAdapterHttpHandlerProfileUpdateProfileRequest }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof putV1Profile>>, TError, { data: InternalAdapterHttpHandlerProfileUpdateProfileRequest }, TContext> => {

  const mutationKey = ['putV1Profile'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putV1Profile>>, { data: InternalAdapterHttpHandlerProfileUpdateProfileRequest }> = (props) => {
    const { data } = props ?? {};

    return putV1Profile(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type PutV1ProfileMutationResult = NonNullable<Awaited<ReturnType<typeof putV1Profile>>>
export type PutV1ProfileMutationBody = InternalAdapterHttpHandlerProfileUpdateProfileRequest
export type PutV1ProfileMutationError = MerrmidErrorResponse

/**
* @summary Update profile
*/
export const usePutV1Profile = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof putV1Profile>>, TError, { data: InternalAdapterHttpHandlerProfileUpdateProfileRequest }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof putV1Profile>>,
      TError,
      { data: InternalAdapterHttpHandlerProfileUpdateProfileRequest },
      TContext
    > => {
  return useMutation(getPutV1ProfileMutationOptions(options), queryClient);
}

/**
 * Register a new user with identity and password
 * @summary Register user
 */
export type postV1RegisterResponse201 = {
  data: InternalAdapterHttpHandlerUserRegisterResponse
  status: 201
}

export type postV1RegisterResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1RegisterResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}

export type postV1RegisterResponseSuccess = (postV1RegisterResponse201) & {
  headers: Headers;
};
export type postV1RegisterResponseError = (postV1RegisterResponse400 | postV1RegisterResponse500) & {
  headers: Headers;
};

export type postV1RegisterResponse = (postV1RegisterResponseSuccess | postV1RegisterResponseError)

export const getPostV1RegisterUrl = () => {




  return `https://accounts.mandacode.com/api/v1/register`
}

export const postV1Register = async (internalAdapterHttpHandlerUserRegisterRequest: InternalAdapterHttpHandlerUserRegisterRequest, options?: RequestInit): Promise<postV1RegisterResponse> => {

  const res = await fetch(getPostV1RegisterUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        internalAdapterHttpHandlerUserRegisterRequest,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postV1RegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1RegisterResponse
}




export const getPostV1RegisterMutationOptions = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1Register>>, TError, { data: InternalAdapterHttpHandlerUserRegisterRequest }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof postV1Register>>, TError, { data: InternalAdapterHttpHandlerUserRegisterRequest }, TContext> => {

  const mutationKey = ['postV1Register'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Register>>, { data: InternalAdapterHttpHandlerUserRegisterRequest }> = (props) => {
    const { data } = props ?? {};

    return postV1Register(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type PostV1RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Register>>>
export type PostV1RegisterMutationBody = InternalAdapterHttpHandlerUserRegisterRequest
export type PostV1RegisterMutationError = MerrmidErrorResponse

/**
* @summary Register user
*/
export const usePostV1Register = <TError = MerrmidErrorResponse,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postV1Register>>, TError, { data: InternalAdapterHttpHandlerUserRegisterRequest }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof postV1Register>>,
      TError,
      { data: InternalAdapterHttpHandlerUserRegisterRequest },
      TContext
    > => {
  return useMutation(getPostV1RegisterMutationOptions(options), queryClient);
}
