/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication service API
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

export interface InternalAdapterHttpHandlerAuthLoginInitLoginRequest {
  id: string;
  password: string;
}

export interface InternalAdapterHttpHandlerAuthLoginInitLoginResponse {
  mfa_methods?: string[];
  mfa_required?: boolean;
  pending_token?: string;
}

export interface InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest {
  pending_token: string;
}

export interface InternalAdapterHttpHandlerAuthLoginNoMFALoginResponse {
  access_token?: string;
}

export interface InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest {
  pending_token: string;
  totp_code: string;
}

export interface InternalAdapterHttpHandlerAuthLoginVerifyTOTPResponse {
  access_token?: string;
}

export interface InternalAdapterHttpHandlerAuthSessionLogoutRequest {
  refresh_token: string;
}

export interface InternalAdapterHttpHandlerAuthSessionLogoutResponse {
  message?: string;
}

export interface InternalAdapterHttpHandlerAuthTokenRefreshTokenResponse {
  access_token?: string;
  refresh_token?: string;
}

export interface InternalAdapterHttpHandlerUserRegisterRequest {
  identity: string;
  /** @minLength 8 */
  password: string;
}

export interface InternalAdapterHttpHandlerUserRegisterResponse {
  message?: string;
}

export type MerrErrCode = typeof MerrErrCode[keyof typeof MerrErrCode];


export const MerrErrCode = {
  ErrUnknown: 0,
  ErrInternal: 1,
  ErrNotFound: 2,
  ErrTimeout: 3,
  ErrInvalidInput: 4,
  ErrPermissionDenied: 5,
  ErrForbidden: 6,
  ErrConflict: 7,
  ErrUnauthorized: 8,
  ErrBadRequest: 9,
  ErrServiceUnavailable: 10,
  ErrTooManyRequests: 11,
  ErrNotImplemented: 12,
  ErrLoopDetected: 13,
  errCodeEnd: 14,
} as const;

export interface MerrmidErrorResponse {
  code?: MerrErrCode;
  error?: string;
}

export interface PasswordChangePasswordRequest {
  /** @minLength 8 */
  new_password: string;
}

export interface PasswordChangePasswordResponse {
  message?: string;
}

/**
 * Logout the user by invalidating the refresh token
 * @summary Logout
 */
export type postV1AuthLogoutResponse200 = {
  data: InternalAdapterHttpHandlerAuthSessionLogoutResponse
  status: 200
}

export type postV1AuthLogoutResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1AuthLogoutResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1AuthLogoutResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1AuthLogoutResponseSuccess = (postV1AuthLogoutResponse200) & {
  headers: Headers;
};
export type postV1AuthLogoutResponseError = (postV1AuthLogoutResponse400 | postV1AuthLogoutResponse401 | postV1AuthLogoutResponse500) & {
  headers: Headers;
};

export type postV1AuthLogoutResponse = (postV1AuthLogoutResponseSuccess | postV1AuthLogoutResponseError)

export const getPostV1AuthLogoutUrl = () => {


  

  return `/v1/auth/logout`
}

export const postV1AuthLogout = async (internalAdapterHttpHandlerAuthSessionLogoutRequest: InternalAdapterHttpHandlerAuthSessionLogoutRequest, options?: RequestInit): Promise<postV1AuthLogoutResponse> => {
  
  const res = await fetch(getPostV1AuthLogoutUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalAdapterHttpHandlerAuthSessionLogoutRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1AuthLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1AuthLogoutResponse
}




export const getPostV1AuthLogoutMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,{data: InternalAdapterHttpHandlerAuthSessionLogoutRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,{data: InternalAdapterHttpHandlerAuthSessionLogoutRequest}, TContext> => {

const mutationKey = ['postV1AuthLogout'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthLogout>>, {data: InternalAdapterHttpHandlerAuthSessionLogoutRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthLogout(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthLogout>>>
    export type PostV1AuthLogoutMutationBody = InternalAdapterHttpHandlerAuthSessionLogoutRequest
    export type PostV1AuthLogoutMutationError = MerrmidErrorResponse

    /**
 * @summary Logout
 */
export const usePostV1AuthLogout = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthLogout>>, TError,{data: InternalAdapterHttpHandlerAuthSessionLogoutRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthLogout>>,
        TError,
        {data: InternalAdapterHttpHandlerAuthSessionLogoutRequest},
        TContext
      > => {
      return useMutation(getPostV1AuthLogoutMutationOptions(options), queryClient);
    }
    
/**
 * Change the authenticated user's password
 * @summary Change password
 */
export type postV1AuthPasswordResponse200 = {
  data: PasswordChangePasswordResponse
  status: 200
}

export type postV1AuthPasswordResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1AuthPasswordResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1AuthPasswordResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1AuthPasswordResponseSuccess = (postV1AuthPasswordResponse200) & {
  headers: Headers;
};
export type postV1AuthPasswordResponseError = (postV1AuthPasswordResponse400 | postV1AuthPasswordResponse401 | postV1AuthPasswordResponse500) & {
  headers: Headers;
};

export type postV1AuthPasswordResponse = (postV1AuthPasswordResponseSuccess | postV1AuthPasswordResponseError)

export const getPostV1AuthPasswordUrl = () => {


  

  return `/v1/auth/password`
}

export const postV1AuthPassword = async (passwordChangePasswordRequest: PasswordChangePasswordRequest, options?: RequestInit): Promise<postV1AuthPasswordResponse> => {
  
  const res = await fetch(getPostV1AuthPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      passwordChangePasswordRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1AuthPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1AuthPasswordResponse
}




export const getPostV1AuthPasswordMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPassword>>, TError,{data: PasswordChangePasswordRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPassword>>, TError,{data: PasswordChangePasswordRequest}, TContext> => {

const mutationKey = ['postV1AuthPassword'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1AuthPassword>>, {data: PasswordChangePasswordRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1AuthPassword(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1AuthPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postV1AuthPassword>>>
    export type PostV1AuthPasswordMutationBody = PasswordChangePasswordRequest
    export type PostV1AuthPasswordMutationError = MerrmidErrorResponse

    /**
 * @summary Change password
 */
export const usePostV1AuthPassword = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1AuthPassword>>, TError,{data: PasswordChangePasswordRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1AuthPassword>>,
        TError,
        {data: PasswordChangePasswordRequest},
        TContext
      > => {
      return useMutation(getPostV1AuthPasswordMutationOptions(options), queryClient);
    }
    
/**
 * Initiate the login process with identity and password
 * @summary Initiate login
 */
export type postV1LoginResponse200 = {
  data: InternalAdapterHttpHandlerAuthLoginInitLoginResponse
  status: 200
}

export type postV1LoginResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1LoginResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1LoginResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1LoginResponseSuccess = (postV1LoginResponse200) & {
  headers: Headers;
};
export type postV1LoginResponseError = (postV1LoginResponse400 | postV1LoginResponse401 | postV1LoginResponse500) & {
  headers: Headers;
};

export type postV1LoginResponse = (postV1LoginResponseSuccess | postV1LoginResponseError)

export const getPostV1LoginUrl = () => {


  

  return `/v1/login`
}

export const postV1Login = async (internalAdapterHttpHandlerAuthLoginInitLoginRequest: InternalAdapterHttpHandlerAuthLoginInitLoginRequest, options?: RequestInit): Promise<postV1LoginResponse> => {
  
  const res = await fetch(getPostV1LoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalAdapterHttpHandlerAuthLoginInitLoginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1LoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1LoginResponse
}




export const getPostV1LoginMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Login>>, TError,{data: InternalAdapterHttpHandlerAuthLoginInitLoginRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1Login>>, TError,{data: InternalAdapterHttpHandlerAuthLoginInitLoginRequest}, TContext> => {

const mutationKey = ['postV1Login'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Login>>, {data: InternalAdapterHttpHandlerAuthLoginInitLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1Login(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1LoginMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Login>>>
    export type PostV1LoginMutationBody = InternalAdapterHttpHandlerAuthLoginInitLoginRequest
    export type PostV1LoginMutationError = MerrmidErrorResponse

    /**
 * @summary Initiate login
 */
export const usePostV1Login = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Login>>, TError,{data: InternalAdapterHttpHandlerAuthLoginInitLoginRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1Login>>,
        TError,
        {data: InternalAdapterHttpHandlerAuthLoginInitLoginRequest},
        TContext
      > => {
      return useMutation(getPostV1LoginMutationOptions(options), queryClient);
    }
    
/**
 * Complete the login process for users without MFA enabled
 * @summary Complete login (no MFA)
 */
export type postV1LoginCompleteNoMfaResponse200 = {
  data: InternalAdapterHttpHandlerAuthLoginNoMFALoginResponse
  status: 200
}

export type postV1LoginCompleteNoMfaResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1LoginCompleteNoMfaResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1LoginCompleteNoMfaResponseSuccess = (postV1LoginCompleteNoMfaResponse200) & {
  headers: Headers;
};
export type postV1LoginCompleteNoMfaResponseError = (postV1LoginCompleteNoMfaResponse400 | postV1LoginCompleteNoMfaResponse500) & {
  headers: Headers;
};

export type postV1LoginCompleteNoMfaResponse = (postV1LoginCompleteNoMfaResponseSuccess | postV1LoginCompleteNoMfaResponseError)

export const getPostV1LoginCompleteNoMfaUrl = () => {


  

  return `/v1/login/complete-no-mfa`
}

export const postV1LoginCompleteNoMfa = async (internalAdapterHttpHandlerAuthLoginNoMFALoginRequest: InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest, options?: RequestInit): Promise<postV1LoginCompleteNoMfaResponse> => {
  
  const res = await fetch(getPostV1LoginCompleteNoMfaUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalAdapterHttpHandlerAuthLoginNoMFALoginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1LoginCompleteNoMfaResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1LoginCompleteNoMfaResponse
}




export const getPostV1LoginCompleteNoMfaMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1LoginCompleteNoMfa>>, TError,{data: InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1LoginCompleteNoMfa>>, TError,{data: InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest}, TContext> => {

const mutationKey = ['postV1LoginCompleteNoMfa'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1LoginCompleteNoMfa>>, {data: InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1LoginCompleteNoMfa(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1LoginCompleteNoMfaMutationResult = NonNullable<Awaited<ReturnType<typeof postV1LoginCompleteNoMfa>>>
    export type PostV1LoginCompleteNoMfaMutationBody = InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest
    export type PostV1LoginCompleteNoMfaMutationError = MerrmidErrorResponse

    /**
 * @summary Complete login (no MFA)
 */
export const usePostV1LoginCompleteNoMfa = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1LoginCompleteNoMfa>>, TError,{data: InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1LoginCompleteNoMfa>>,
        TError,
        {data: InternalAdapterHttpHandlerAuthLoginNoMFALoginRequest},
        TContext
      > => {
      return useMutation(getPostV1LoginCompleteNoMfaMutationOptions(options), queryClient);
    }
    
/**
 * Complete the login process with TOTP (Time-based One-Time Password) verification
 * @summary Complete login (TOTP)
 */
export type postV1LoginCompleteTotpResponse200 = {
  data: InternalAdapterHttpHandlerAuthLoginVerifyTOTPResponse
  status: 200
}

export type postV1LoginCompleteTotpResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1LoginCompleteTotpResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1LoginCompleteTotpResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1LoginCompleteTotpResponseSuccess = (postV1LoginCompleteTotpResponse200) & {
  headers: Headers;
};
export type postV1LoginCompleteTotpResponseError = (postV1LoginCompleteTotpResponse400 | postV1LoginCompleteTotpResponse401 | postV1LoginCompleteTotpResponse500) & {
  headers: Headers;
};

export type postV1LoginCompleteTotpResponse = (postV1LoginCompleteTotpResponseSuccess | postV1LoginCompleteTotpResponseError)

export const getPostV1LoginCompleteTotpUrl = () => {


  

  return `/v1/login/complete-totp`
}

export const postV1LoginCompleteTotp = async (internalAdapterHttpHandlerAuthLoginVerifyTOTPRequest: InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest, options?: RequestInit): Promise<postV1LoginCompleteTotpResponse> => {
  
  const res = await fetch(getPostV1LoginCompleteTotpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalAdapterHttpHandlerAuthLoginVerifyTOTPRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1LoginCompleteTotpResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1LoginCompleteTotpResponse
}




export const getPostV1LoginCompleteTotpMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1LoginCompleteTotp>>, TError,{data: InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1LoginCompleteTotp>>, TError,{data: InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest}, TContext> => {

const mutationKey = ['postV1LoginCompleteTotp'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1LoginCompleteTotp>>, {data: InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1LoginCompleteTotp(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1LoginCompleteTotpMutationResult = NonNullable<Awaited<ReturnType<typeof postV1LoginCompleteTotp>>>
    export type PostV1LoginCompleteTotpMutationBody = InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest
    export type PostV1LoginCompleteTotpMutationError = MerrmidErrorResponse

    /**
 * @summary Complete login (TOTP)
 */
export const usePostV1LoginCompleteTotp = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1LoginCompleteTotp>>, TError,{data: InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1LoginCompleteTotp>>,
        TError,
        {data: InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest},
        TContext
      > => {
      return useMutation(getPostV1LoginCompleteTotpMutationOptions(options), queryClient);
    }
    
/**
 * Register a new user with identity and password
 * @summary Register user
 */
export type postV1RegisterResponse201 = {
  data: InternalAdapterHttpHandlerUserRegisterResponse
  status: 201
}

export type postV1RegisterResponse400 = {
  data: MerrmidErrorResponse
  status: 400
}

export type postV1RegisterResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1RegisterResponseSuccess = (postV1RegisterResponse201) & {
  headers: Headers;
};
export type postV1RegisterResponseError = (postV1RegisterResponse400 | postV1RegisterResponse500) & {
  headers: Headers;
};

export type postV1RegisterResponse = (postV1RegisterResponseSuccess | postV1RegisterResponseError)

export const getPostV1RegisterUrl = () => {


  

  return `/v1/register`
}

export const postV1Register = async (internalAdapterHttpHandlerUserRegisterRequest: InternalAdapterHttpHandlerUserRegisterRequest, options?: RequestInit): Promise<postV1RegisterResponse> => {
  
  const res = await fetch(getPostV1RegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      internalAdapterHttpHandlerUserRegisterRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1RegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1RegisterResponse
}




export const getPostV1RegisterMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Register>>, TError,{data: InternalAdapterHttpHandlerUserRegisterRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1Register>>, TError,{data: InternalAdapterHttpHandlerUserRegisterRequest}, TContext> => {

const mutationKey = ['postV1Register'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1Register>>, {data: InternalAdapterHttpHandlerUserRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postV1Register(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postV1Register>>>
    export type PostV1RegisterMutationBody = InternalAdapterHttpHandlerUserRegisterRequest
    export type PostV1RegisterMutationError = MerrmidErrorResponse

    /**
 * @summary Register user
 */
export const usePostV1Register = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1Register>>, TError,{data: InternalAdapterHttpHandlerUserRegisterRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1Register>>,
        TError,
        {data: InternalAdapterHttpHandlerUserRegisterRequest},
        TContext
      > => {
      return useMutation(getPostV1RegisterMutationOptions(options), queryClient);
    }
    
/**
 * Refresh the access token using a refresh token from session cookie
 * @summary Refresh token
 */
export type postV1TokenRefreshResponse200 = {
  data: InternalAdapterHttpHandlerAuthTokenRefreshTokenResponse
  status: 200
}

export type postV1TokenRefreshResponse401 = {
  data: MerrmidErrorResponse
  status: 401
}

export type postV1TokenRefreshResponse500 = {
  data: MerrmidErrorResponse
  status: 500
}
    
export type postV1TokenRefreshResponseSuccess = (postV1TokenRefreshResponse200) & {
  headers: Headers;
};
export type postV1TokenRefreshResponseError = (postV1TokenRefreshResponse401 | postV1TokenRefreshResponse500) & {
  headers: Headers;
};

export type postV1TokenRefreshResponse = (postV1TokenRefreshResponseSuccess | postV1TokenRefreshResponseError)

export const getPostV1TokenRefreshUrl = () => {


  

  return `/v1/token/refresh`
}

export const postV1TokenRefresh = async ( options?: RequestInit): Promise<postV1TokenRefreshResponse> => {
  
  const res = await fetch(getPostV1TokenRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postV1TokenRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postV1TokenRefreshResponse
}




export const getPostV1TokenRefreshMutationOptions = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TokenRefresh>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postV1TokenRefresh>>, TError,void, TContext> => {

const mutationKey = ['postV1TokenRefresh'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postV1TokenRefresh>>, void> = () => {
          

          return  postV1TokenRefresh(fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostV1TokenRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postV1TokenRefresh>>>
    
    export type PostV1TokenRefreshMutationError = MerrmidErrorResponse

    /**
 * @summary Refresh token
 */
export const usePostV1TokenRefresh = <TError = MerrmidErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postV1TokenRefresh>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postV1TokenRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostV1TokenRefreshMutationOptions(options), queryClient);
    }
