/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication service API
 * OpenAPI spec version: 1.0
 */

export interface InternalAdapterHttpHandlerAuthLoginVerifyTOTPRequest {
  pending_token: string;
  totp_code: string;
}
