/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication service API
 * OpenAPI spec version: 1.0
 */
import type { MerrErrCode } from "./merrErrCode";

export interface MerrmidErrorResponse {
  code?: MerrErrCode;
  error?: string;
}
