/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication service API
 * OpenAPI spec version: 1.0
 */

export type MerrErrCode = (typeof MerrErrCode)[keyof typeof MerrErrCode];

export const MerrErrCode = {
  ErrUnknown: 0,
  ErrInternal: 1,
  ErrNotFound: 2,
  ErrTimeout: 3,
  ErrInvalidInput: 4,
  ErrPermissionDenied: 5,
  ErrForbidden: 6,
  ErrConflict: 7,
  ErrUnauthorized: 8,
  ErrBadRequest: 9,
  ErrServiceUnavailable: 10,
  ErrTooManyRequests: 11,
  ErrNotImplemented: 12,
  ErrLoopDetected: 13,
  errCodeEnd: 14,
} as const;
