/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Auth API
 * Authentication service API
 * OpenAPI spec version: 1.0
 */

export interface PasswordChangePasswordRequest {
  /** @minLength 8 */
  new_password: string;
}
