/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Accounts API
 * Accounts management service API
 * OpenAPI spec version: 1.0
 */

export interface InternalAdapterHttpHandlerMfaRemoveMFAResponse {
  message?: string;
}
